const modules = [
  { topic: "Lesson 0–2: Welcome & Blockchain Basics" },
  { topic: "Lesson 3: Remix Storage Factory" },
  { topic: "Lesson 4: Remix Fund Me" },
  { topic: "Lesson 5: Ethers.js Simple Storage" },
  { topic: "Lesson 6: Hardhat Simple Storage" },
  { topic: "Lesson 7: Hardhat Fund Me" },
  { topic: "Lesson 8: HTML / Javascript Fund Me" },
  { topic: "Lesson 9: Hardhat Smart Contract Lottery" },
  { topic: "Lesson 10: NextJS Smart Contract Lottery" },
  { topic: "Lesson 11: Hardhat Starter Kit" },
  { topic: "Lesson 12: Hardhat ERC20s" },
  { topic: "Lesson 13: Hardhat DeFi & Aave" },
  { topic: "Lesson 14: Hardhat NFTs" },
  { topic: "Lesson 15: NextJS NFT Marketplace" },
  { topic: "Lesson 16: Hardhat Upgrades" },
  { topic: "Lesson 17: Hardhat DAOs" },
  { topic: "Lesson 18: Security & Auditing" },
];